server:
  port: 8081

  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://192.168.31.176:5432/amigoscode
    username: amigoscode
    password: password

  #  --------------How to turn off web server--------------
#spring:
#  main:
#    web-application-type: none
#----------------------------------------------------------
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

